require('./reservation.test');
require('./table.test');
require('./restaurantReservations.test');
require('./repositoryManager.test');
require('./restaurantReservationsManager.test');
require('./eventHandlerManager.test');
require('./query.test');
require('./integration.test');
require('./denormalizer');
