#%RAML 1.0
---
title: Reservation Service API
mediaType: application/json
version: v1
protocols: [ HTTP, HTTPS ]
baseUri: api.reservation_service.com/{version}
schemas: 
    Error:
        properties:
            error: string
    UUID:
        type: string
        pattern: ^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$
    Table:
        properties:
            tableId: string
            people: integer
    Reservation:
        properties:
            restId: UUID
            resId: UUID
            userId: UUID
            reservationName: string
            people: integer
            date: datetime
            status: string
            table?: Table   

/reservations:
    get:
        description: Get reservations of an user if userId is specified or the reservations of a restaurant if restId is specified
        headers: 
        queryParameters:
                userId:
                    description: Specify the user id of which it's getting the reservations
                    required: false
                    type: string
                    example: 0553dec2-8e58-4639-ae0c-620e9022b3c6
                restId:
                    description: Specify the restaurant id of which it's getting the reservations
                    required: false
                    type: string
                    example: 0553dec2-8e58-4639-ae0c-620e9022b3c6                
        responses: 
            200:
                body:
                    application/json:
                        type: Reservation[]
            400:
                body:
                    application/json:
    post:
        description: Creates a new reservation
        headers: 
        body: 
            application/json:
                properties:
                    restId: UUID
                    userId: UUID
                    people: integer
                    date: datetime
        responses: 
            200:
                body:
                    application/json:
            400:
                body:
                    application/json:
                        type: Error

    /{resId}:
        get:
            description: Get the reservation by id
            headers:
            responses:
                200:
                    body:
                        application/json:
                            type: Reservation
                400:
                    body:
                        application/json:
                            type: Error
                404:
                    body:
                        application/json:
                            type: Error
        /status:
            get:
                description: Get the reservation status
                headers:
                responses:
                    200:
                        body:
                            application/json:
                                properties:
                                    resId: UUID
                                    status: string
                    400:
                        body:
                            application/json:
                                type: Error
                    404:
                        body:
                            application/json:
                                type: Error
            put:
                description: Update the reservation status
                headers:
                body:
                    application/json:
                        properties:
                            restId?: UUID
                            status: string

                responses:
                    200:
                    400:
                        body:
                            application/json:
                                type: Error
                    404:
                        body:
                            application/json:
                                type: Error

# /reservation:
#     get:
#         description: Gets a resevation
#         headers:
#         queryParameters:
#             resId: 
#                 description: The reservation id
#                 required: true
#                 type: UUID
#                 example: 0553dec2-8e58-4639-ae0c-620e9022b3c6
#         responses:
#             200:
#                 body:
#                     application/json:
#                         type: Reservation
#             404:
#                 body:
#                     application/json:
#                         type: Reservation
