#%RAML 1.0
---
title: Reservation Service API
version: v1
baseUri: api.reservation_service.com/{version}
schemas: 
    Reservation:
        properties:
            restId: string
            resId: string
            people: integer
            date: datetime
            status: string
            table?: Table
/reservation:
    post:
        description: Creates a new reservation
        headers: 
        body: 
            application/json:
                properties:
                    restId: string
                    people: integer
                    date: datetime
                    # userId MUST be added
                    # userId: string
        responses: 
            200:
                body:
                    application/json:
            400:
                body:
                    application/json:
/reservations:
    get:
        description: Get reservations of an user if userId is specified or the reservations of a restaurant if restId is specified
        headers: 
        queryParameters:
                userId:
                    description: Specify the user id of which it's getting the reservations
                    required: false
                    type: string
                    example: 0553dec2-8e58-4639-ae0c-620e9022b3c6
                restId:
                    description: Specify the restaurant id of which it's getting the reservations
                    required: false
                    type: string
                    example: 0553dec2-8e58-4639-ae0c-620e9022b3c6                
        responses: 
            200:
                body:
                    application/json:
                        type: Reservation[]
            400:
                body:
                    application/json: